### ISSUE TITLE
Solution fails to modify capital letters in input string

### ISSUE THREAD

**Issue by Polyphemus** [ZLester/Coderbyte-Solutions#3]
According to specs: Replace every letter in the string with the letter following it in the alphabet (c becomes d, z becomes a). Then capitalize every vowel in this new string (a, e, i, o, u) and finally return this modified string. 

If the input string contains a capital letter ("Argument goes here" for example), the capital letters will not be modified as they are not contained by the alpha string "abcdefghijklmnopqrstuvwxyz".

Output for "Argument goes here" is "AshvnfOU hpft Ifsf" but should be "BshvnfOU hpft Ifsf". 

This could be solved by modifying alpha and newalpha as follows: 
  var alpha = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
  var newAlpha = "bcdEfghIjklmnOpqrstUvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZA";

**Comment by ZLester** [comment]
The challenge doesn't mention what should be done with capital letters (and none of the test cases include capital letters in the input string), so both the current solution and your proposed modification will receive full points. Regardless, I'm all for capturing more edge cases – feel free to pull against the repo to improve this (or any other) solution.
